-- Setup tables for Engram - the hyper-localized social network
-- IMPORTANT: If you already have the old engrams/votes tables, this script will NOT add the new columns.
-- Run the MIGRATION section below first if upgrading from the old Bulletin schema.

-- ============================================================
-- MIGRATION: Add new columns to existing tables (run this first if upgrading)
-- ============================================================
-- Uncomment and run these if you already have engrams/votes tables:

-- ALTER TABLE public.engrams ADD COLUMN IF NOT EXISTS geotopic_id BIGINT REFERENCES public.geotopics(id) ON DELETE SET NULL;
-- ALTER TABLE public.engrams ADD COLUMN IF NOT EXISTS location_name TEXT;
-- ALTER TABLE public.engrams ADD COLUMN IF NOT EXISTS weekly_score INTEGER DEFAULT 0;
-- CREATE INDEX IF NOT EXISTS engrams_geotopic_idx ON public.engrams (geotopic_id);
-- CREATE INDEX IF NOT EXISTS engrams_weekly_score_idx ON public.engrams (weekly_score DESC);
-- CREATE INDEX IF NOT EXISTS engrams_created_at_idx ON public.engrams (created_at DESC);

-- ALTER TABLE public.geotopics ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('emerging', 'active', 'trending', 'archived'));
-- ALTER TABLE public.geotopics ADD COLUMN IF NOT EXISTS embedding VECTOR(1536);
-- CREATE INDEX IF NOT EXISTS geotopics_embedding_idx ON public.geotopics USING ivfflat (embedding vector_cosine_ops);
-- CREATE INDEX IF NOT EXISTS geotopics_status_idx ON public.geotopics (status);
-- UPDATE public.geotopics SET status = 'active' WHERE status IS NULL;

-- ============================================================
-- FRESH INSTALL: Create all tables from scratch
-- ============================================================

-- Enable pgvector extension for embedding similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Create the geotopics table (hyper-localized communities)
CREATE TABLE IF NOT EXISTS public.geotopics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    location_name TEXT NOT NULL, -- e.g. "Philadelphia", "NYC", "Brooklyn"
    location_lat DECIMAL(10, 8), -- optional precise lat
    location_lng DECIMAL(11, 8), -- optional precise lng
    topic TEXT NOT NULL, -- e.g. "Music Shows", "Startups", "Food"
    created_by TEXT DEFAULT 'user' CHECK (created_by IN ('user', 'ai')), -- who created it
    post_count INTEGER DEFAULT 0,
    weekly_score INTEGER DEFAULT 0, -- aggregate score for trending
    status TEXT DEFAULT 'emerging' CHECK (status IN ('emerging', 'active', 'trending', 'archived')),
    embedding VECTOR(1536), -- for semantic similarity matching
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create the engrams (posts) table - updated for geotopics
CREATE TABLE IF NOT EXISTS public.engrams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    device_id TEXT NULL, -- Device identifier for anonymous posting
    cluster TEXT DEFAULT 'general',
    geotopic_id BIGINT REFERENCES public.geotopics(id) ON DELETE SET NULL,
    location_name TEXT, -- denormalized from geotopic for quick display
    upvotes INTEGER DEFAULT 0,
    downvotes INTEGER DEFAULT 0,
    weekly_score INTEGER DEFAULT 0, -- computed score for leaderboard
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create the votes table to track user votes (using client-generated IDs)
CREATE TABLE IF NOT EXISTS public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engram_id BIGINT REFERENCES public.engrams(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL, -- Use device ID instead of user_id for anonymous voting
    vote_type TEXT NOT NULL CHECK (vote_type IN ('up', 'down')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (engram_id, device_id) -- Ensure one vote per device per engram
);

-- Create the leaderboard_snapshots table for weekly historical leaderboards
CREATE TABLE IF NOT EXISTS public.leaderboard_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engram_id BIGINT REFERENCES public.engrams(id) ON DELETE CASCADE,
    rank INTEGER NOT NULL,
    score INTEGER NOT NULL,
    upvotes INTEGER NOT NULL,
    downvotes INTEGER NOT NULL,
    week_start DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS geotopics_location_idx ON public.geotopics (location_name);
CREATE INDEX IF NOT EXISTS geotopics_topic_idx ON public.geotopics (topic);
CREATE INDEX IF NOT EXISTS geotopics_slug_idx ON public.geotopics (slug);
CREATE INDEX IF NOT EXISTS geotopics_weekly_score_idx ON public.geotopics (weekly_score DESC);
CREATE INDEX IF NOT EXISTS geotopics_status_idx ON public.geotopics (status);
CREATE INDEX IF NOT EXISTS geotopics_embedding_idx ON public.geotopics USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS engrams_cluster_idx ON public.engrams (cluster);
CREATE INDEX IF NOT EXISTS engrams_device_id_idx ON public.engrams (device_id);
CREATE INDEX IF NOT EXISTS engrams_geotopic_idx ON public.engrams (geotopic_id);
CREATE INDEX IF NOT EXISTS engrams_weekly_score_idx ON public.engrams (weekly_score DESC);
CREATE INDEX IF NOT EXISTS engrams_created_at_idx ON public.engrams (created_at DESC);
CREATE INDEX IF NOT EXISTS votes_engram_id_idx ON public.votes (engram_id);
CREATE INDEX IF NOT EXISTS votes_device_id_idx ON public.votes (device_id);
CREATE INDEX IF NOT EXISTS leaderboard_week_start_idx ON public.leaderboard_snapshots (week_start DESC);

-- Set up Row Level Security (RLS) policies for anonymous access

-- Enable RLS on the tables
ALTER TABLE public.engrams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.geotopics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_snapshots ENABLE ROW LEVEL SECURITY;

-- ENGRAM POLICIES
CREATE POLICY "Anyone can read engrams"
ON public.engrams FOR SELECT
USING (true);

CREATE POLICY "Anyone can create engrams"
ON public.engrams FOR INSERT
WITH CHECK (true);

CREATE POLICY "Anyone can update engrams"
ON public.engrams FOR UPDATE
USING (true);

CREATE POLICY "Anyone can delete engrams"
ON public.engrams FOR DELETE
USING (true);

-- VOTES POLICIES
CREATE POLICY "Anyone can read votes"
ON public.votes FOR SELECT
USING (true);

CREATE POLICY "Anyone can create votes"
ON public.votes FOR INSERT
WITH CHECK (true);

CREATE POLICY "Anyone can update votes"
ON public.votes FOR UPDATE
USING (true);

CREATE POLICY "Anyone can delete votes"
ON public.votes FOR DELETE
USING (true);

-- GEOTOPICS POLICIES
CREATE POLICY "Anyone can read geotopics"
ON public.geotopics FOR SELECT
USING (true);

CREATE POLICY "Anyone can create geotopics"
ON public.geotopics FOR INSERT
WITH CHECK (true);

CREATE POLICY "Anyone can update geotopics"
ON public.geotopics FOR UPDATE
USING (true);

-- LEADERBOARD SNAPSHOTS POLICIES
CREATE POLICY "Anyone can read leaderboard snapshots"
ON public.leaderboard_snapshots FOR SELECT
USING (true);

-- Insert some seed geotopics
INSERT INTO public.geotopics (name, slug, description, location_name, topic, created_by, status)
VALUES
    ('General', 'general', 'The global community feed', 'Global', 'General', 'user', 'active'),
    ('Music Shows in Philly', 'music-shows-in-philly', 'Live music, concerts, and shows around Philadelphia', 'Philadelphia', 'Music Shows', 'user', 'active'),
    ('Startups in NYC', 'startups-in-nyc', 'Startup ecosystem, fundraising, and founder events in New York City', 'New York City', 'Startups', 'user', 'active'),
    ('Food in Austin', 'food-in-austin', 'Best tacos, BBQ, and food trucks in Austin', 'Austin', 'Food', 'user', 'active'),
    ('Hiking in Denver', 'hiking-in-denver', 'Trail recommendations and hiking groups near Denver', 'Denver', 'Hiking', 'user', 'active'),
    ('Tech in SF', 'tech-in-sf', 'Bay Area tech news, meetups, and job postings', 'San Francisco', 'Tech', 'user', 'active')
ON CONFLICT (slug) DO NOTHING;
