-- Migration: add contact_info to engrams and create replies table
-- Run this in the Supabase SQL Editor if you already have the Bulletin schema.

-- Optional contact info (email, IG, phone, etc.) shown on posts
ALTER TABLE public.engrams ADD COLUMN IF NOT EXISTS contact_info TEXT;

-- Replies/comments on posts
CREATE TABLE IF NOT EXISTS public.replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engram_id BIGINT REFERENCES public.engrams(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS replies_engram_id_idx ON public.replies (engram_id);
CREATE INDEX IF NOT EXISTS replies_created_at_idx ON public.replies (created_at DESC);

-- Anonymous RLS policies (same style as the rest of the app)
ALTER TABLE public.replies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read replies" ON public.replies;
CREATE POLICY "Anyone can read replies"
ON public.replies FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Anyone can create replies" ON public.replies;
CREATE POLICY "Anyone can create replies"
ON public.replies FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can update replies" ON public.replies;
CREATE POLICY "Anyone can update replies"
ON public.replies FOR UPDATE
USING (true);

DROP POLICY IF EXISTS "Anyone can delete replies" ON public.replies;
CREATE POLICY "Anyone can delete replies"
ON public.replies FOR DELETE
USING (true);
